[package]
name = "p4rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num = { version = "0.4", features = ["serde"] }
bitvec = "1.0"
usdt.workspace = true
serde = "1.0"

[dev-dependencies]
pnet = "0.31"
